<?php
$payment = $block->getOrder()->getPayment();
$method = $payment->getMethodInstance()->getCode();
?>
<?php if ($method == 'sample_gateway') :?>
<div class="admin__page-section-item-content">
    <strong><?php echo __('Account Name:') ?></strong>
    <span class="price"><?php echo $payment->getData('bankowner'); ?></span>                        
    <strong><?php echo __('Bank Name:') ?></strong>
    <span class="price"><?php echo $payment->getData('bankname'); ?></span>
    <strong><?php echo __('Banck Number:') ?></strong>
    <span class="price"><?php echo $payment->getData('banknumber'); ?></span>
</div>
<?php endif; ?>